# fly.toml app configuration file generated for ethos-interview-be on 2025-06-14T18:36:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ethos-interview-be'
primary_region = 'sin'

[build]

[env]
MONGODB_URI = "mongodb+srv://alwi:PulauLangit97@cluster0.rworcg7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
PORT = "8080"
CLOUDINARY_PUBLISHABLE_KEY = "12"
CLOUDINARY_SECRET_KEY = "12"
CLOUDINARY_CLOUD_NAME = "12"
CURRENCY = "IDR"
JWT_SECRET = "secret123"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
